import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Events",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=" w-full">
      <div className="  relative w-full h-screen ">{children}</div>
    </div>
  );
}
