import AuthHeader from "@/components/shared/layout/authHeaders";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Events Auth by ISCE",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=" w-full">
      <AuthHeader
        hasLink={false}
        message="Hang tight, while we take you through our account setup process, this
        will not take up much of your time."
      />
      <div className=" p-[20px] relative w-full h-screen ">{children}</div>
    </div>
  );
}
